### ISSUE TITLE
sensor.fordpass_doorstatus 

### ISSUE THREAD

**Issue by gniknalu** [itchannel/fordpass-ha#126]
My current `sensor.fordpass_doorstatus` is:

```rightRearDoor: Closed
leftRearDoor: Closed
driverDoor: Ajar
passengerDoor: Closed
hoodDoor: Closed
tailgateDoor: Closed
innerTailgateDoor: Closed
friendly_name: fordpass_doorStatus
icon: mdi:car-door
```

It was last updated 6 hours ago. At that time the `driverDoor` was closed and had been closed since the previous day. Is there a way to get more updated status? What triggers an update (because the vehicle hadn't been running since the previous day)? Would LOVE to make an automation based on the door status! (Also window status to give an alert if it's raining and the windows are open.)

**Thank you for this excellent project!**

**Comment by itchannel** [comment]
At least on my cars an update is triggered when unlocking the car but not when locking etc. I recommend you setup an automation to call the refresh_status service which will poll the car for the latest update. However as its quite battery intensive I would tie it to another automation such as "When person A arrives home, poll the car for update 15 mins later"

**Comment by Antoine-Hurstel** [comment]
Hello, 
another way to trigger the refresh when leaving the vehicle is to check when your mobile phone gets disconnected from the vehicle's bluetooth. 
I've added 5 min delay between bluetooth disconnexion and trigger to get some time to leave and lock the vehicle, since the bluetooth gets disconnected as soon as the driver door is opened. 
This automation is working at any location, but requires a remote access to Home assistant from the mobile phone.
