### ISSUE TITLE
Change Username / Password / VIN?

### ISSUE THREAD

**Issue by J-T-W** [itchannel/fordpass-ha#163]
Once configured, how do I update/change the username / password / vin in HA?

**Comment by itchannel** [comment]
Unfortunately the only way currently is to delete and add the integration again. I do have in the future to add the authentication parameters as options but not currently.

**Comment by J-T-W** [comment]
Good to know - thanks!

**Comment by DevTodd** [comment]
@J-T-W - I recently called Ford and they reset my password without even asking.  Since I have about 20 automation there was no way in hell I was going to redo all of those so here's the steps to change the information

Disable the FP integration 
Restart
make the .storage directory available or cd to it in term
edit core.config_entries 
change your username/password/VIN
save
enable the integration
restart
profit
