### ISSUE TITLE
FordPass account locout due to using 3rd party app.

### ISSUE THREAD

**Issue by Boomer50BMG** [itchannel/fordpass-ha#229]
My FordPass account was suspended due to using it with fordpass-ha.  I was told by Ford support that I had to disable the 3rd party app for my account to be unlocked.

**Comment by fasteddie-g** [comment]
Same, started about 3 weeks ago, and finally got it unlocked today.  I was receiving error code "CSIAH0320E" when I would try to login with the FordPass App.  

I had the FordPass App, Amazon Alexa integration, and HomeAssistant HACS integration.

The rep said it was known this was impacting customers, and was a security control possibly due to too many integrations with the same email address.  The rep suggested I create separate accounts (each with a unique email address) for each integration so that the Ford security ecosystem doesn't see anomalous activity from multiple integrations on a single account, but rather consistent activity for each integration on its own account.  Plus if one gets locked out again, it won't impact the others.

**Comment by itchannel** [comment]
Closing as there's been no further complaints and 15min poll interval seems to have prevented further lockouts.
