### ISSUE TITLE
Feature Request: Ability to Change Charging Mode

### ISSUE THREAD

**Issue by BadgerLoaf** [itchannel/fordpass-ha#237]
Would it be possible to have the ability to change between "Charge when plugged in" and "Use preferred charge settings" for a location? 

I have a use case where I want to be able to change from my scheduled charge, to 'boost' the car during my peak electricity time (by changing it to 'Charge when plugged in' for a period of time. 

Thanks for the consideration and all your work on this integration.

![IMG_94E37C5F8F26-1](https://user-images.githubusercontent.com/108699847/211157073-42e55269-139b-4ea7-8e6e-d73bf13135cd.jpeg)

**Comment by CoreyD97** [comment]
In addition to this, a sensor to know if the car is plugged in would be great. The fordpass app can detect if the charger is plugged in even when there's no power to it, so it'd be great to have this as a sensor for automations.

**Comment by Bert-R** [comment]
@CoreyD97 That's already available as attribute. I have an automation that warns when the range is less than X and the car is not plugged in. The latter condition looks like this:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/7149792/214831306-a44a67c2-987b-4c22-9112-0e4e25269e4c.png">

**Comment by CoreyD97** [comment]
Ah, I hadn't thought to check the attributes, thanks for pointing this out.

**Comment by Yashi577** [comment]
Great work on he integation! I would also love to see the ablity to chnage the charge seetings. This would add some useful capability to control charging with unsmart chargers!

**Comment by CoreyD97** [comment]
This is something I'd love to see implemented. I was using a smart switch to connect/cut the power to the charger depending on the electric price for a couple of months but unfortunately have just burnt out two switches in a week because of how much power the charger draws. 

If this could be implemented my poor switches would be grateful :)

**Comment by SquidBytes** [comment]
I'm going to close this since the last comment is from April, and there have been large changes since then.

For specific charging stopping and starting - it is being looked into #357 
If we are able to get charging stopping and starting then HA could be used as a charging mode, but we could also look into the charging mode.
Please open a new issue for any new issues :)
