### ISSUE TITLE
Allow Selection of Imperial vs Metric Units

### ISSUE THREAD

**Issue by tonesto7** [itchannel/fordpass-ha#24]
Thanks very much for your work.  
Can you please add an option to allow for imperial units for fuel and mileage?

**Comment by itchannel** [comment]
Definitely something I'll look at adding, trying to work out if there's a way I can pick the region up from home assistant to be automatic. 

In the meantime you can add a template sensor to convert to miles then just reference that sensor like below:

`- platform: template
  sensors:
    fordpass_odmiles:
      friendly_name: "Ford Odometer Miles"
      value_template: "{{ (states('sensor.fordpass_odometer')|float/1.60934)|round(0) }}"`

**Comment by TRusselo** [comment]
home assistant uses User Locale (Language) to set other region specific settings, it is a per-user setting...  in HA click your user icon in sidebar.

But it would screw us Canadians...  we use English (US) in home assistant as there is no English (CA).
There is an English (GB) but due to the recent update to Home Assistant Calendar integration, if you have English (GB) selected as language, it now shows all Calendars start on Monday (GROSS AS HELL).  you have to select English (US) to get calendars to start on Sunday....

**Comment by itchannel** [comment]
@TRusselo Can you confirm if the number returned for the odometer is in miles or km for you. Ignore the extension just need to see if it returns km for everyone or whether it returns miles instead. Before I go and convert the value.

**Comment by Madseason41** [comment]
KM for me and I am in the southern U.S. I just came here to figure out how to get fuel and mileage to show in U.S. gallons and miles.

**Comment by itchannel** [comment]
@Madseason41 Can I confirm that the value you see is KM and not just miles with the KM tag. Trying to check if all regions return the value in KM or whether it returns different depending on region. If it's the same I can just add a conversion function and a nice imperial/metric option but need to check first.

**Comment by Madseason41** [comment]
Ah yes, its actually km. Vehicle has around 74k miles and 119k km is displayed in the custom integration.

**Comment by itchannel** [comment]
Great. Then I'll add in a Metric/Imperial option to the integration then you can choose how you want it displayed

**Comment by TRusselo** [comment]
my van dash, ford app and HA all say 2603 KM

**Comment by itchannel** [comment]
Latest version now allows you to set imperial or metric in the options. (Small bug not showing a title for options but still works fine)
