### ISSUE TITLE
fordpass_gps Status

### ISSUE THREAD

**Issue by afp316** [itchannel/fordpass-ha#255]
My fordpass_gps status has been UNSHIFTED for the time I've had my mach-e (5 months).  Do I need to change any settings to get the gps to work?

**Comment by rtw819** [comment]
For what it is worth, you are not the only one.  I have an automation that watches for vehicle arrival into the "Home" zone that hasn't fired since September 30, 2022.  I'm not sure the GPS location data is being reported the same way any more.  It used to work!  No idea what changed.

**Comment by itchannel** [comment]
I recommend pulling data from the fordpass_tracker entity rather than fordpass_gps which is just a sensor provided from the API. The tracker entity is a proper GPS entity and will show the Zone and GPS coordinates. 

In the meantime I will check the fordpass_gps data to see if the API structure has changed slightly.

**Comment by rtw819** [comment]
Hmm.  The fordpass_gps subsystem does not appear to update beyond "UNSHIFTED" even when a vehicle travels hours away. 

It might be worth noting the precision of the device_tracker.fordpass_tracker response results in just 2 decimal points where the sensor.fordpass_gps has 6 digits after the decimal -- I'm not sure if that would make a huge accuracy difference for folks or not.

I'm going to open a separate issue to track what I have going on with my automation so that I don't hijack this thread.

**Comment by itchannel** [comment]
The precision of the coordinates on the sensor.fordpass_tracker is set to 2 decimals which is what's required for Home Assistant tracker entities. It gives you an accuracy of a couple of meters which is more than enough 👍 

The "UNSHIFTED" state is what's taken from the API entity so it might be that Ford have stopped changing the value and only updating the coordinates now but I'll try and run some tests.

**Comment by Genieplumb** [comment]
This is also happening for me too. its been two weeks without an update. let me know if you need any info from me to help out. or run tests cheers

**Comment by itchannel** [comment]
@Genieplumb Can you see if the fordpass_tracker is being updated including the GPS coordinates in the attributes.

**Comment by tesmerjg** [comment]
me too, 
_-- like some braindead aol'er_

**Comment by Greminn** [comment]
FYI, fordpass_tracker works perfectly for me and it is used for Home/Away automations, but fordpass_gps is always UNSHIFTED.

**Comment by itchannel** [comment]
The fordpass_gps sensor status is taken from the API
```
"gps":{"latitude":"-1******","longitude":"1*******","gpsState":"UNSHIFTED","status":"CURRENT","timestamp":"07-06-2023 02:59:11"
```

It seems to display "UNSHIFTED" most of the time, hence why you should use the device_tracker entity instead which uses the current GPS coordinates from the GPS entity and ignores the current status. I did think of removing this sensor as it is somewhat pointless but have left it in in case it does change status for certain models.

**Comment by itchannel** [comment]
Closing as the fordpass_gps is set from the API's gps key which the gpsState generally shows as shifted. Recommend always using the device_tracker entity as this is updated from the precise coordinates.
