### ISSUE TITLE
Feature request: higher refresh rate when the car is moving

### ISSUE THREAD

**Issue by xaviersand** [itchannel/fordpass-ha#268]
I've set the refresh rate to 15 min; it would be nice to have another refresh rate when the car is in movement, as i'm logging the gps coordinates too; it would be nice to poll every 3 minutes when the gps coordinate moves more than X

**Comment by JeffCrum1** [comment]
I don't think you want to go under five minutes due to possibly being locked out by Ford.

But, there is a way to do what you want  Although, I am not always seeing the refresh work.

fordpass.refresh_status

You can set a five minute timer, build an automation that calls the refresh and restarts the timer when timer.finished.

**Comment by itchannel** [comment]
New service in 1.47 (Pre Release) called "poll_api" which can be used by automations to pull data from the API on demand. Just be warned doing this too often could result in a ban.

**Comment by magnetic157** [comment]
I created an automation in Node Red that pulls more frequently when the ignition is on and back to normal frequency when the ignition is off.  I don't usually travel too far though, so if I was on a long road trip, i'd likely disable that.  I've had it like this for the past year and so far no issues.

**Comment by xaviersand** [comment]
Hi, would it be possible somehow to share the nodered automation ? I actually don't know how to change these kind of "constants"

**Comment by itchannel** [comment]
Closing old issue for housekeeping

Please reopen if the issue is still present :)
