### ISSUE TITLE
1.58 Beta - Temps way off

### ISSUE THREAD

**Issue by magnetic157** [itchannel/fordpass-ha#373]
My FordPass was showing "Unavailable" for all my entities the last couple days so I upgraded to the 1.58 BETA but now my temp sensors seem way off.  My car has been in the garage unused for the last 24 hours.

<img width="404" alt="image" src="https://github.com/itchannel/fordpass-ha/assets/78054864/e1d360db-da48-4c65-b5cf-328a008c01e1">

**Comment by SquidBytes** [comment]
Have you verified your car isn't on fire?

Joking aside, yes its known and will be fixed in 1.58 (if you want it fixed now you can replace the sensor.py file and restart)

It was a bug introduced because I added conversions in the code for C to F.
We then moved over to having HomeAssistant do the conversions for specific sensors, which caused certain values to be converted multiple times. 
https://github.com/itchannel/fordpass-ha/commit/bc01aa9af987dc1e8e263a0bb2ef25efa86617a7
