### ISSUE TITLE
Estimated Charge End Time problem in 1.58

### ISSUE THREAD

**Issue by pbryan7** [itchannel/fordpass-ha#386]
Prior to 1.58 the 'Time to Complete' charging data was accurate.   In the 1.58 release the change to 'Estimated End Time' has an issue.   

Currently it's saying my estimated end time is ~4 hours different than the Ford Pass App.   Seeing as I'm in the -4 timezone, perhaps this is a timezone issue.

Current HA Data:
Estimated End Time: '2023-10-20T05:39:34-04:00'
Ford Pass App:  10/20 @ 1:32 AM

**Comment by pbryan7** [comment]
Just did an api update on both HA & the phone...    the charge complete times are now exactly 4 hours apart...   I'm feeling pretty certain this is a time zone related issue...

**Comment by SquidBytes** [comment]
Yes, I noticed that while looking into lastRefresh.
Working on it now

**Comment by SquidBytes** [comment]
If you modify your `sensor.py` file
Line 501 to 504
![image](https://github.com/itchannel/fordpass-ha/assets/145411069/b09e6800-d5c0-447a-a572-8eb226dcfd04)

Change it to be like this
`                    cs_update_time = dt.parse_datetime(self.data["xevBatteryTimeToFullCharge"]["updateTime"])
                    cs_est_end_time = cs_update_time + timedelta(minutes=self.data["xevBatteryTimeToFullCharge"]["value"])
                    cs["Estimated End Time"] = dt.as_local(cs_est_end_time)`

That should fix it, but I can't 100% guarantee right now because I'm not charging, so my time is off.

**Comment by SquidBytes** [comment]
Hey @pbryan7, just wanted to make sure this was resolved. If you haven't updated, it should be fixed now.

**Comment by pbryan7** [comment]
Yep, Seems to be working fine now.
