### ISSUE TITLE
Wrong gps location

### ISSUE THREAD

**Issue by doronazl** [itchannel/fordpass-ha#391]
i keep getting getting wrong location,  went out 6 hours ago, car location updated correclty, then went back home, the location is still showing as the car is at that location, and not home , which is about 15km from where i am
im not blaming the integration, as i just checked, the gps location on the ford app is showing the same wrong location

**Comment by itchannel** [comment]
I've noticed the API isn't the best at updating data. Out of interest do you have bad mobile signal where you live? As I do which is why it doesn't always update/respond. 

You could also try manually running "refresh_status" when you get home e.g. phone is detected by HA which would then give you updated data.

**Comment by doronazl** [comment]
No signal issue.
How do i run that command?

**Comment by SquidBytes** [comment]
@doronazl Are you still having this issue?
