### ISSUE TITLE
How do I access EV data?

### ISSUE THREAD

**Issue by koehntopp** [itchannel/fordpass-ha#419]
Just installed the integration and activated it, but I can't figure out how to access data for my Mustang Mach-E.

I'm primarily interested in battery charge, range and mileage, but the existing entities have nothing of the sort.

Any help appreciated.

**Comment by SquidBytes** [comment]
Once you have setup the integration there should be sensors that are populated.
For EV specific there should be a
`fordpass_elVeh` and fordpass_elVehCharging` sensor.

Depending on which build you got there might be an issue with them displaying.
The previous release 1.60 had a few issues that should be resolved in the Beta versions of 1.61
And 1.61 should be out soon, which fixes those issues and adds a few new things.

**Comment by koehntopp** [comment]
> For EV specific there should be a
> fordpass_elVeh and fordpass_elVehCharging sensor.

I installed the beta, but I'm still struggling with the value templates. I've looked at https://github.com/itchannel/fordpass-ha/issues/123#issuecomment-1050303476 , but the attribute names seem to have changed.

Given this is a HA integration, it would be great if the template.yaml entries were readily available here...

**Comment by koehntopp** [comment]
Got it.

In template.yaml:

`    - name: "Mustang Reichweite"
      unit_of_measurement: "km"
      device_class: distance
      state_class: measurement
      state: "{{ states('sensor.fordpass_elVeh') | round(0) }}"

    - name: "Mustang Akku"
      unit_of_measurement: "%"
      device_class: battery
      state_class: measurement
      state: "{{ state_attr('sensor.fordpass_elVeh', 'Battery Actual Charge') | round(0) }}"
`

**Comment by SquidBytes** [comment]
Yes, the names have changed because we the API changed I started adding all the information I could into the integration. We have also moved over to having HomeAssistant do the conversions as the default returned from the vehicle is metric.
I changed some names to make it clearer to the user which value is which.
For example, the integration used to just have a State of Charge. But now its able to return the State of Charge....and actual state of charge from the vehicles json. I've also added a dedicated charging sensor that returns more charging information.

> Given this is a HA integration, it would be great if the template.yaml entries were readily available here...
That is a good suggestion. With the large variety and the custom nature of each persons setup it would probably have to be community generated.

From the #123 conversation, if you would like to use those templates, this updated version should work

`
template:
  - sensor:
    - name: "your name for range"
      unique_id: "id you want"
      state: "{{ state('sensor.fordpass_elVeh') }}"
  - sensor:
    - name: "your name for the battery level"
      unique_id: "id you want"
      state: "{{state_attr('sensor.fordpass_elVeh', ' Battery Charge') }}"
      unit_of_measurement: "%"`
  - sensor:
    - name: "your name for the ENTIRE battery level"
      unique_id: "id you want"
      state: "{{state_attr('sensor.fordpass_elVeh', ' Battery Actual Charge') }}"
      unit_of_measurement: "%"
`

Keep in mind, the Battery Charge is what is generally displayed from the FordPass app and in the vehicle.
Generally manufactures keep a "reserve" amount in the battery.
The Actual Charge is the entire battery, including that "reserve" amount.
