### ISSUE TITLE
is there a way to get charging history

### ISSUE THREAD

**Issue by Donni1966** [itchannel/fordpass-ha#424]
First of all - **thanx a lot for coding this HA-integration**. I like it and it helps me to set up my dashboards and spezial automatics to include my mustang mach-e in the house automations. 

With my last e-car (MINI COOPER SE) i get a history of charging ( every month) and this let me show my charging history in my smarthome. are there any further  things you will implementing or dose ford not provide this informations in the API? 

I see the protocol in the ford app so i hope this will available on the API. 

thanx for the answers.

**Comment by SquidBytes** [comment]
Charge Logs are in the FordPass app, but I believe they only store around 20.

It is accessible from the API, but to add it to this integration it would need a few things. I know this because it's how I got started (see below)

I don't believe returning the charge logs into HomeAssistant would be that useful because it's just data, and I don't see it working as something like a sensor.


### SELF PLUG - NOT RELATED TO THIS INTEGRATION 
I wanted better logs than what the Ford app gave me, so I started making my own thing.
During that process, I discovered this integration and have since become a contributor.

I am still working on my own thing, separate from this integration, but I'm in the process of trying to migrate over to using a different database.
I initially created it with postgres. I thought the API changes broke it, but just the other day I leaned I was able to get it working.

If you're fairly techy, you could get it working, but for now I still need to do many updates to it...but I'm working on it when I can.
I wrote it with my Lightning in mind, but I believe it will work with Mach-Es.

If you would like, you can follow it here: https://github.com/SquidBytes/LightningROD

I imagine within the next week or so I'll have it in a decent state for other people to use.

**Comment by Donni1966** [comment]
> Charge Logs are in the FordPass app, but I believe they only store around 20.

That's why I'm looking for a way to secure them. 

I use Node-red myself to backup my running data to an influx DB. But I think sensors could already be created with the number of charging processes and the total kw power per month for example. I guess others could use such a solution as well. Therefore my question. 

>if you're fairly techy, you could get it working, but for now I still need to do many updates to it...but I'm >working on it when I can.
>I wrote it with my Lightning in mind, but I believe it will work with Mach-Es.

I'll definitely take a look at that. 
I used a node-red integration with the BMW Mini that supported a JSON file that documented all charging events. That's where I pulled my data from and put it on my dashboard(s). 
And since, as I said, not all data remains in the FordApp, I find it nice to prepare it myself. by month, charging point and so on. 

I will follow you on your project :-) Thanx but i am not a good coder. So this job can do others better.

**Comment by SquidBytes** [comment]
> That's why I'm looking for a way to secure them.
Same, which led me down this path.

>  I think sensors could already be created with the number of charging processes and the total kw power per month for example.
Yes, with the attributes I have been adding under the various elVeh sensors, you should be able to grab the data and log it from those existing sensors. This would be "real time" charging data being logged.

My other project, LightningROD, is mimicking the Charge Logs tab in the FordPass app, which is only updated a few hours after each charge. It is also dependent upon the data that is logged in that area - which doesn't include extra things returned "live" like Battery Temperature.

I have goals to make LightningROD work with different options like WITH or WITHOUT HomeAssistant. I just need time to work on it, and since the API changes I have been busy with everything else.
