### ISSUE TITLE
How do we install the 1.70 version in HACS?

### ISSUE THREAD

**Issue by GerwinVerkerk** [itchannel/fordpass-ha#540]
Hello, I want to run the 1.70 version since the login is broken in previous version. However, when trying to install the fordpass integration and selecting show beta version, it doesn't pop up. How do I install this fork?

![issue](https://github.com/user-attachments/assets/0a0911b7-ed9a-4ffb-9134-d819f1bf19b3)

**Comment by vhs-ex** [comment]
Per the note on the 1.70 token page, it is manual since this fork is still being developed.
[https://github.com/itchannel/fordpass-ha/wiki/Obtaining-Tokens-(As-of-25-05-2024)](url)

`This requires the [1.70 branch](https://github.com/itchannel/fordpass-ha/tree/1.70) as this has not been fully detected you will need to manually grab the files to test`

If you already have an older version installed, I believe you can just manually replace the files with the ones for 1.70

**Comment by TheLizard** [comment]
Actually, it is nicely described in another comment: https://github.com/itchannel/fordpass-ha/issues/488#issuecomment-2305308642
