### ISSUE TITLE
Rear windows report incorrectly

### ISSUE THREAD

**Issue by jimmychanga** [itchannel/fordpass-ha#68]
Current version: 1.12
2019 Ford Edge ST

DriverWindowPosition
Fully_Closed
PassWindowPosition
Fully_Closed
RearDriverWindowPos
Undefined
RearPassWindowPos
Undefined

**Comment by itchannel** [comment]
Do you have rear windows in your car?

**Comment by jimmychanga** [comment]
Well yeah, it’s why I’m reporting it :)

It’s a SUV.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by itchannel** [comment]
Out of interest are they electric windows in the rear of your car? Also are those the only window values you seen when viewing the window entity. As it looks like your car can't give readings for the rear windows. I can add "Undefined" to the filter so they will no longer report as "Open"

**Comment by jimmychanga** [comment]
Yes, they are electric.

As of the latest version, the front windows report the correct status and the rear windows report undefined.

In the previous version, all 4 windows showed as Open.

Joe Marr
C: 704-773-1985
E: joe.marr@bodiddely.com<mailto:joe.marr@bodiddely.com>

**Comment by itchannel** [comment]
The previous version didn't take into account the status of "Undefined" where as the new one does. It looks like your rear windows do not support "statuses" on my new pickup it doesn't support window statuses for any windows. The easiest fix is to add "Undefined" to the array so it won't report it as Open anymore for the entire group. It will continue to report Undefined for the individual status but the actual state of the main entity will report "Closed" instead of "open" all th time.

**Comment by jimmychanga** [comment]
Thats fine, I figured you would want to know. The FordPass app does show correct statuses, so I suspect the issue lies more with Ford's external facing API. Where are you pulling this data from, I can try to troubleshoot the issue myself.

**Comment by itchannel** [comment]
Interesting as it uses the exact same API the ford app uses. If you have time run the following [Debug](https://github.com/itchannel/ford_debug) script which will log to a txt file all the calls. The one your interested in is the last one which contains a big json array of all the statuses. If you can grab out the "WindowPosition" array from that I can check to see how your statuses are different from what I currently grab.

**Comment by jimmychanga** [comment]
Here ya go:

'windowPosition': {
	'driverWindowPosition': {
		'value': 'Fully_Closed', 
		'status': 'CURRENT', 
		'timestamp': '12-30-2020 00:36:47'}, 
	'passWindowPosition': {
		'value': 'Fully_Closed', 
		'status': 'CURRENT', 
		'timestamp': '12-30-2020 00:36:47'}, 
	'rearDriverWindowPos': {
		'value': 'Undefined', 
		'status': 'CURRENT', 
		'timestamp': '12-30-2020 00:36:47'},
	'rearPassWindowPos': {
		'value': 'Undefined', 
		'status': 'CURRENT', 
		'timestamp': '12-30-2020 00:36:47'}
}

**Comment by itchannel** [comment]
So that is exactly what the integration is seeing "Undefined" for 2 of your windows. So your fordpass app either must not show the status of those back 2 windows or it lies and just says "Closed". As the integration and that debug script uses exactly the same  API endpoint. 

I'll add in so it doesn't show "Undefined" statuses as open and if you ever find those two windows show anything other than "Undefined" later on we can revisit it

**Comment by jimmychanga** [comment]
Ok, cool. I'll run the debug periodically and let you know if anything changes. In the future, if you need help testing or troubleshooting issues, let me know.

**Comment by itchannel** [comment]
Closing for now as original issue was fixed and other part wasn't supported.
